### ISSUE TITLE
It eat too much ram on Chrome

### ISSUE THREAD

**Issue by longnight** [blocknomic-technologies/open-trading-platform-UI#6]
**Describe the bug**
Website eat Chrome ram too much.

**To Reproduce**
Just current version,  run on local development machine.

**Expected behavior**
Hope to improve on browser ram consume.

**Desktop (please complete the following information):**
 - OS: Linux & Windows
 - Browser:  chrome

**Comment by g666nz** [comment]
Hi,
Currently we don't have the resources to develop on this. But if you are able to find a viable solution you can fork it and put in a pull request

**Comment by longnight** [comment]
Thanks anyway.
